---
abstract: 'Basic HTTP authentication for Dancer web apps'
author:
  - 'Michal Wojciechowski <odyniec@cpan.org>'
build_requires:
  Pod::Select: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Auth-Basic
provides:
  Dancer::Plugin::Auth::Basic:
    file: lib/Dancer/Plugin/Auth/Basic.pm
    version: 0.01
requires:
  Dancer: 1.307
  HTTP::Headers: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
